import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import AppSidebar from "@/components/AppSidebar";
import {ThemeProvider} from "@/components/theme-provider";
import {SidebarProvider} from "@/components/ui/sidebar";
import {cookies} from "next/headers";
import {Montserrat} from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ['latin']
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.variable} antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
          <SidebarProvider defaultOpen={defaultOpen}>
              <AppSidebar/>
              <main className='w-full'>
                  <NavBar/>
                  <div className='px-4'>
                      {children}
                  </div>

              </main>
          </SidebarProvider>

      </ThemeProvider>
      </body>
    </html>
  );
}
